Created method to generate string in Commit 9a0727c6. Created test calling for sdf_file_or_string to generate sdf_string without H atom. For #3
Test failure message:
(my-rdkit-env) [qyuan@ch-qyuan-z440 ccd_utils]$ nosetests -v test_pdb_chemical_components_rdkit.py 2>&1 | egrep 'non-empty str'
test_pdb_chemical_components_rdkit.test_load_eoh_from_cif(True, 'sdf_file_or_string must create a non-empty str') ... ok
test_pdb_chemical_components_rdkit.test_load_eoh_from_cif(True, 'sdf_file_or_string must create a non-empty str') ... ok
test_pdb_chemical_components_rdkit.test_load_eoh_from_cif(' H ', '\n     RDKit          3D\n\n  9  8  0  0  0  0  0  0  0  0999 V2000\n    0.0070   -0.5690    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.2850    0.2500   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.1300    0.3150   -0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0390   -1.1970    0.8900 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0390   -1.1970   -0.8900 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.3170    0.8780    0.8900 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.3170    0.8780   -0.8900 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.1420   -0.4240    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.9860   -0.1370    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\n  1  3  1  0\n  1  4  1  0\n  1  5  1  0\n  2  6  1  0\n  2  7  1  0\n  2  8  1  0\n  3  9  1  0\nA    1\nC1\nA    2\nC2\nA    3\nO\nA    4\nH11\nA    5\nH12\nA    6\nH21\nA    7\nH22\nA    8\nH23\nA    9\nHO\nM  END\n', 'sdf_file_or_string must create a non-empty str without H atom') ... FAIL
test_pdb_chemical_components_rdkit.test_load_eoh_from_cif(' H ', '\n     RDKit          3D\n\n  9  8  0  0  0  0  0  0  0  0999 V2000\n   15.2120   49.1980    7.4910 C   0  0  0  0  0  0  0  0  0  0  0  0\n   16.0690   50.3860    7.1040 C   0  0  0  0  0  0  0  0  0  0  0  0\n   15.8610   48.1850    8.2560 O   0  0  0  0  0  0  0  0  0  0  0  0\n   14.3750   49.5790    8.0940 H   0  0  0  0  0  0  0  0  0  0  0  0\n   14.8580   48.7310    6.5600 H   0  0  0  0  0  0  0  0  0  0  0  0\n   15.4670   51.0980    6.5200 H   0  0  0  0  0  0  0  0  0  0  0  0\n   16.4420   50.8800    8.0130 H   0  0  0  0  0  0  0  0  0  0  0  0\n   16.9200   50.0420    6.4980 H   0  0  0  0  0  0  0  0  0  0  0  0\n   15.2440   47.4880    8.4470 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\n  1  3  1  0\n  1  4  1  0\n  1  5  1  0\n  2  6  1  0\n  2  7  1  0\n  2  8  1  0\n  3  9  1  0\nA    1\nC1\nA    2\nC2\nA    3\nO\nA    4\nH11\nA    5\nH12\nA    6\nH21\nA    7\nH22\nA    8\nH23\nA    9\nHO\nM  END\n', 'sdf_file_or_string must create a non-empty str without H atom') ... FAIL
FAIL: test_pdb_chemical_components_rdkit.test_load_eoh_from_cif(' H ', '\n     RDKit          3D\n\n  9  8  0  0  0  0  0  0  0  0999 V2000\n    0.0070   -0.5690    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.2850    0.2500   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.1300    0.3150   -0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0390   -1.1970    0.8900 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0390   -1.1970   -0.8900 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.3170    0.8780    0.8900 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.3170    0.8780   -0.8900 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.1420   -0.4240    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n    1.9860   -0.1370    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\n  1  3  1  0\n  1  4  1  0\n  1  5  1  0\n  2  6  1  0\n  2  7  1  0\n  2  8  1  0\n  3  9  1  0\nA    1\nC1\nA    2\nC2\nA    3\nO\nA    4\nH11\nA    5\nH12\nA    6\nH21\nA    7\nH22\nA    8\nH23\nA    9\nHO\nM  END\n', 'sdf_file_or_string must create a non-empty str without H atom')
AssertionError: sdf_file_or_string must create a non-empty str without H atom
FAIL: test_pdb_chemical_components_rdkit.test_load_eoh_from_cif(' H ', '\n     RDKit          3D\n\n  9  8  0  0  0  0  0  0  0  0999 V2000\n   15.2120   49.1980    7.4910 C   0  0  0  0  0  0  0  0  0  0  0  0\n   16.0690   50.3860    7.1040 C   0  0  0  0  0  0  0  0  0  0  0  0\n   15.8610   48.1850    8.2560 O   0  0  0  0  0  0  0  0  0  0  0  0\n   14.3750   49.5790    8.0940 H   0  0  0  0  0  0  0  0  0  0  0  0\n   14.8580   48.7310    6.5600 H   0  0  0  0  0  0  0  0  0  0  0  0\n   15.4670   51.0980    6.5200 H   0  0  0  0  0  0  0  0  0  0  0  0\n   16.4420   50.8800    8.0130 H   0  0  0  0  0  0  0  0  0  0  0  0\n   16.9200   50.0420    6.4980 H   0  0  0  0  0  0  0  0  0  0  0  0\n   15.2440   47.4880    8.4470 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\n  1  3  1  0\n  1  4  1  0\n  1  5  1  0\n  2  6  1  0\n  2  7  1  0\n  2  8  1  0\n  3  9  1  0\nA    1\nC1\nA    2\nC2\nA    3\nO\nA    4\nH11\nA    5\nH12\nA    6\nH21\nA    7\nH22\nA    8\nH23\nA    9\nHO\nM  END\n', 'sdf_file_or_string must create a non-empty str without H atom')
AssertionError: sdf_file_or_string must create a non-empty str without H atom