Add ASX.cif to test files examples as it element 'X' that causes problems.
Obtained file from /nfs/ftp/pub/databases/msd/pdbechem/files/mmcif/ASX.cif  current PDBeChem

For issue #17 "process_components_cif_cli.py: handle complete components.cif"

Unit test failure:
    (new-rdkit-env3) [osmart@swannandrh6d ccd_utils]$ nosetests tests/test_pdb_ccd_rdkit_loading.py
    ...........[16:28:36] Explicit valence for atom # 2 Be, 4, is greater than permitted
    [16:28:36] Explicit valence for atom # 2 Be, 4, is greater than permitted
    [16:28:36] Explicit valence for atom # 2 Be greater than permitted
    ..[16:28:37] Explicit valence for atom # 20 C, 5, is greater than permitted
    [16:28:37] Explicit valence for atom # 20 C, 5, is greater than permitted
    [16:28:37] Explicit valence for atom # 20 C greater than permitted
    .[16:28:37] Explicit valence for atom # 0 B, 6, is greater than permitted
    [16:28:37] Explicit valence for atom # 0 B, 5, is greater than permitted
    [16:28:37] WARNING: Accepted unusual valence(s): B(6); C(6)
    .[16:28:37] WARNING: Proton(s) added/removed
    .[16:28:37]

    ****
    Post-condition Violation
    Element 'X' not found
    Violation occurred on line 90 in file /opt/conda/conda-bld/rdkit_1496744127279/work/Code/GraphMol/PeriodicTable.h
    Failed Expression: anum > -1
    ****

    E
    ======================================================================
    ERROR: Failure: RuntimeError (Post-condition Violation
        Element 'X' not found
        Violation occurred on line 90 in file Code/GraphMol/PeriodicTable.h
        Failed Expression: anum > -1
        RDKIT: 2017.03.2
        BOOST: 1_56
    )
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
        for test in g():
      File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/tests/test_pdb_ccd_rdkit_loading.py", line 44, in test_inchikey_match_for_all_sample_cifs
        pdb_cc = PdbChemicalComponentsRDKit(file_name=ciffile)
      File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 36, in __init__
        self.__setup_rdkit_mol()
      File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 51, in __setup_rdkit_mol
        self.__setup_atoms()
      File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 77, in __setup_atoms
        rdkit_atom = Chem.Atom(element)
    RuntimeError: Post-condition Violation
        Element 'X' not found
        Violation occurred on line 90 in file Code/GraphMol/PeriodicTable.h
        Failed Expression: anum > -1
        RDKIT: 2017.03.2
        BOOST: 1_56

    ----------------------------------------------------------------------
    Ran 17 tests in 0.124s

    FAILED (errors=1)