chem_comp_xml creation for single ccd: unit test extra items from GLU test for SMILES*2, inchi and systematic name.
For issue #10 "Create chem.xml for all components"

Initially get expected failure because not yet implemented:
(new-rdkit-env) osmart@fuji01vm:~/ccd_utils$ nosetests -v tests/test_pdb_chemical_components.py^C
        ERROR: Failure: AttributeError ('PdbChemicalComponents' object has no attribute 'smiles_cactvs')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/home/osmart/anaconda/envs/new-rdkit-env/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
            for test in g():
          File "/home/osmart/ccd_utils/tests/test_pdb_chemical_components.py", line 109, in test_load_glu_from_cif
            yield assert_equals, 'N[CH](CCC(O)=O)C(O)=O', glu.smiles_cactvs, \
        AttributeError: 'PdbChemicalComponents' object has no attribute 'smiles_cactvs'

        ----------------------------------------------------------------------
        Ran 43 tests in 0.230s

        FAILED (errors=1)