First version of PdbChemicalComponentsRDKit that works (a bit!)
Extended test to do ethanol and this gets passes the inchikey from rdkit matches that from cif file test.
The carbon monoxide inchikey does not match - not yet setting the charge and the carbon needs to be -ve oxygen positive

Test result:
        (new-rdkit-env) [osmart@ebi-cli-003 ccd_utils]$ nosetests -sv test_pdb_chemical_components_rdkit.py
        DEBUG element=C name=C
        DEBUG element=O name=O
        DEBUG bond index_1=0 index_2=1 order=3
        ccd_utils.test_pdb_chemical_components_rdkit.test_hard_code_cmo('CMO', 'CMO', 'chem_comp_id') ... ok
        ccd_utils.test_pdb_chemical_components_rdkit.test_hard_code_cmo('CARBON MONOXIDE', 'CARBON MONOXIDE', 'chem_comp_name') ... ok
        ccd_utils.test_pdb_chemical_components_rdkit.test_hard_code_cmo('UGFAIRIUMAVXCW-UHFFFAOYSA-N', 'UGFAIRIUMAVXCW-UHFFFAOYSA-N', 'chem_inchikey') ... ok
        ccd_utils.test_pdb_chemical_components_rdkit.test_hard_code_cmo(2, 2, 'rdkit_mol.GetNumAtoms() should give 2') ... ok
        [19:18:26] WARNING: Accepted unusual valence(s): O(3)
        ccd_utils.test_pdb_chemical_components_rdkit.test_hard_code_cmo('UGFAIRIUMAVXCW-UHFFFAOYSA-N', 'CFHIDWOYWUOIHU-UHFFFAOYSA-N', 'inchikey from cif file should match the rdkit inchikey') ... FAIL
        DEBUG element=C name=C1
        DEBUG element=C name=C2
        DEBUG element=O name=O
        DEBUG element=H name=H11
        DEBUG element=H name=H12
        DEBUG element=H name=H21
        DEBUG element=H name=H22
        DEBUG element=H name=H23
        DEBUG element=H name=HO
        DEBUG bond index_1=0 index_2=1 order=1
        DEBUG bond index_1=0 index_2=2 order=1
        DEBUG bond index_1=0 index_2=3 order=1
        DEBUG bond index_1=0 index_2=4 order=1
        DEBUG bond index_1=1 index_2=5 order=1
        DEBUG bond index_1=1 index_2=6 order=1
        DEBUG bond index_1=1 index_2=7 order=1
        DEBUG bond index_1=2 index_2=8 order=1
        ccd_utils.test_pdb_chemical_components_rdkit.test_load_eoh_from_cif('EOH', 'EOH', 'chem_comp_id') ... ok
        ccd_utils.test_pdb_chemical_components_rdkit.test_load_eoh_from_cif('LFQSCWFLJHTTHZ-UHFFFAOYSA-N', 'LFQSCWFLJHTTHZ-UHFFFAOYSA-N', 'inchikey from cif file should match the rdkit inchikey') ... ok

        ======================================================================
        FAIL: ccd_utils.test_pdb_chemical_components_rdkit.test_hard_code_cmo('UGFAIRIUMAVXCW-UHFFFAOYSA-N', 'CFHIDWOYWUOIHU-UHFFFAOYSA-N', 'inchikey from cif file should match the rdkit inchikey')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
            self.test(*self.arg)
        AssertionError: inchikey from cif file should match the rdkit inchikey

        ----------------------------------------------------------------------
        Ran 7 tests in 0.037s

        FAILED (failures=1)