Add problem 10R (carborane compound) to list of test ccd cif get exception "ValueError: could not find number of expected rings."
For issue #17 "process_components_cif_cli.py: handle complete components.cif"

File obtained from

ftp://ftp.ebi.ac.uk/pub/databases/msd/pdbechem/files/mmcif/10R.cif

Causes unit test failures in writing sdf and images:

    (new-rdkit-env3) osmart@fuji01vm:~/ccd_utils$ nosetests tests/test_write_sdf.py
    ......................................[12:04:15] Explicit valence for atom # 20 C, 5, is greater than permitted
    [12:04:15] Explicit valence for atom # 20 C, 5, is greater than permitted
    ....[12:04:15] Explicit valence for atom # 0 B, 6, is greater than permitted
    [12:04:15] Explicit valence for atom # 0 B, 5, is greater than permitted
    E
    ======================================================================
    ERROR: Failure: ValueError (could not find number of expected rings.)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/osmart/anaconda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/home/osmart/anaconda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
        for test in g():
      File "/home/osmart/ccd_utils/tests/test_write_sdf.py", line 74, in test_sdf_write_for_all_sample_cifs
        pdb_cc.sdf_file_or_string(file_name=sdf_ideal_with_h)
      File "/home/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 218, in sdf_file_or_string
        sdf_string = Chem.MolToMolBlock(mol_h_select, confId=conformer_id)
    ValueError: could not find number of expected rings.

    ----------------------------------------------------------------------
    Ran 43 tests in 0.263s

    FAILED (errors=1)

        (new-rdkit-env3) osmart@fuji01vm:~/ccd_utils$ nosetests tests/test_write_img.py
        .............[12:06:41] Explicit valence for atom # 20 C, 5, is greater than permitted
        [12:06:41] Explicit valence for atom # 20 C, 5, is greater than permitted
        [12:06:41] Explicit valence for atom # 20 C, 5, is greater than permitted
        [12:06:41] Explicit valence for atom # 0 B, 6, is greater than permitted
        [12:06:41] Explicit valence for atom # 0 B, 5, is greater than permitted
        E.[12:06:41] Explicit valence for atom # 20 C, 5, is greater than permitted
        [12:06:41] Explicit valence for atom # 20 C, 5, is greater than permitted
        [12:06:41] Explicit valence for atom # 20 C, 5, is greater than permitted
        .
        ======================================================================
        ERROR: Failure: ValueError (could not find number of expected rings.)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/home/osmart/anaconda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
            raise self.exc_val.with_traceback(self.tb)
          File "/home/osmart/anaconda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
            for test in g():
          File "/home/osmart/ccd_utils/tests/test_write_img.py", line 53, in test_svg_write_for_all_sample_cifs
            pdb_cc.image_file_or_string(file_name=img_no_h_no_label, hydrogen=False, atom_labels=False)
          File "/home/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 397, in image_file_or_string
            AllChem.GenerateDepictionMatching3DStructure(mol_to_draw, mol_to_draw)
        ValueError: could not find number of expected rings.

        ----------------------------------------------------------------------
        Ran 16 tests in 0.501s

        FAILED (errors=1)