Add 00N.cif to the test cif files as this currently causes a crash. obtained from /nfs/ftp/pub/databases/msd/pdbechem/files/mmcif/00O.cif
For issue #17 "process_components_cif_cli.py: handle complete components.cif"

unit test test_pdb_ccd_rdkit_loading.py reproduces crash:

        (new-rdkit-env3) [osmart@swannandrh6d ccd_utils]$ nosetests tests/test_pdb_ccd_rdkit_loading.py -v
        tests.test_pdb_ccd_rdkit_loading.test_hard_code_cmo('CMO', 'CMO', 'chem_comp_id') ... ok
        tests.test_pdb_ccd_rdkit_loading.test_hard_code_cmo('CARBON MONOXIDE', 'CARBON MONOXIDE', 'chem_comp_name') ... ok
        tests.test_pdb_ccd_rdkit_loading.test_hard_code_cmo('UGFAIRIUMAVXCW-UHFFFAOYSA-N', 'UGFAIRIUMAVXCW-UHFFFAOYSA-N', 'chem_inchikey') ... ok
        tests.test_pdb_ccd_rdkit_loading.test_hard_code_cmo(2, 2, 'rdkit_mol.GetNumAtoms() should give 2') ... ok
        tests.test_pdb_ccd_rdkit_loading.test_hard_code_cmo('UGFAIRIUMAVXCW-UHFFFAOYSA-N', 'UGFAIRIUMAVXCW-UHFFFAOYSA-N', 'inchikey from cif file should match the rdkit inchikey') ... ok
        tests.test_pdb_ccd_rdkit_loading.test_load_eoh_from_cif('EOH', 'EOH', 'chem_comp_id') ... ok
        tests.test_pdb_ccd_rdkit_loading.test_load_eoh_from_cif('LFQSCWFLJHTTHZ-UHFFFAOYSA-N', 'LFQSCWFLJHTTHZ-UHFFFAOYSA-N', 'inchikey from cif file should match the rdkit inchikey') ... ok
        tests.test_pdb_ccd_rdkit_loading.test_inchikey_match_for_all_sample_cifs('CXHHBNMLPJOKQD-UHFFFAOYSA-N', 'CXHHBNMLPJOKQD-UHFFFAOYSA-N', 'check inchikeys match for 000') ... ok
        tests.test_pdb_ccd_rdkit_loading.test_inchikey_match_for_all_sample_cifs('SJWOFBVBNFLWLP-UHFFFAOYSA-N', 'SJWOFBVBNFLWLP-UHFFFAOYSA-N', 'check inchikeys match for 007') ... ok
        Failure: ValueError (could not convert string to float: '?') ... ERROR

        ======================================================================
        ERROR: Failure: ValueError (could not convert string to float: '?')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
            raise self.exc_val.with_traceback(self.tb)
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
            for test in g():
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/tests/test_pdb_ccd_rdkit_loading.py", line 44, in test_inchikey_match_for_all_sample_cifs
            pdb_cc = PdbChemicalComponentsRDKit(file_name=ciffile)
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 36, in __init__
            self.__setup_rdkit_mol()
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 53, in __setup_rdkit_mol
            self.__setup_conformers()
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 132, in __setup_conformers
            (model_x, model_y, model_z) = self.model_xyz[atom_index]
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components.py", line 254, in model_xyz
            float_x = float(atom['model_Cartn_x'])
        ValueError: could not convert string to float: '?'