Add 03R.cif to examples - it has atoms that lack ideal coordinates
For issue #17 "process_components_cif_cli.py: handle complete components.cif"

Causes failure in rdkit loading:
        (new-rdkit-env3) [osmart@swannandrh6d ccd_utils]$ nosetests tests/test_pdb_ccd_rdkit_loading.py
        ..........E
        ======================================================================
        ERROR: Failure: ValueError (could not convert string to float: '?')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
            raise self.exc_val.with_traceback(self.tb)
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
            for test in g():
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/tests/test_pdb_ccd_rdkit_loading.py", line 44, in test_inchikey_match_for_all_sample_cifs
            pdb_cc = PdbChemicalComponentsRDKit(file_name=ciffile)
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 36, in __init__
            self.__setup_rdkit_mol()
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 53, in __setup_rdkit_mol
            self.__setup_conformers()
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 131, in __setup_conformers
            (ideal_x, ideal_y, ideal_z) = self.ideal_xyz[atom_index]
          File "/automount/vnas-msd_vol-vol_msd/work2/osmart/ccd_utils/pdb_chemical_components.py", line 235, in ideal_xyz
            float_x = float(atom['pdbx_model_Cartn_x_ideal'])
        ValueError: could not convert string to float: '?'

        ----------------------------------------------------------------------
        Ran 11 tests in 0.137s

        FAILED (errors=1)