add tests for EOH back.
        They all fail at present because have not implemented any loaded:
        osmart@fuji01vm:~/ccd_utils$ ./test_pdb_chemical_components.py
        ...FFF
        ======================================================================
        FAIL: test_load_EOH_cif_atom_ids_are_correct (__main__.MyTestCase)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "./test_pdb_chemical_components.py", line 31, in test_load_EOH_cif_atom_ids_are_correct
            self.assertEqual(['C1', 'C2',  'O', 'H11', 'H12', 'H21', 'H22', 'H23', 'HO'], self.ccd_eoh.atom_ids)
        AssertionError: Lists differ: ['C1', 'C2', 'O', 'H11', 'H12'... != []

        First list contains 9 additional elements.
        First extra element 0:
        C1

        - ['C1', 'C2', 'O', 'H11', 'H12', 'H21', 'H22', 'H23', 'HO']
        + []

        ======================================================================
        FAIL: test_load_EOH_cif_chem_comp_id_is_EOH (__main__.MyTestCase)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "./test_pdb_chemical_components.py", line 28, in test_load_EOH_cif_chem_comp_id_is_EOH
            self.assertEqual('EOH', self.ccd_eoh.chem_comp_id)
        AssertionError: 'EOH' != None

        ======================================================================
        FAIL: test_load_EOH_number_atoms_is_9 (__main__.MyTestCase)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "./test_pdb_chemical_components.py", line 34, in test_load_EOH_number_atoms_is_9
            self.assertEqual(9, self.ccd_eoh.number_atoms)
        AssertionError: 9 != 0

        ----------------------------------------------------------------------
        Ran 6 tests in 0.011s

        FAILED (failures=3)