Implement method write_ccd_cif. Unit test shows it works, but need to implement __eq__ method for pdb_chemical_components.py to fully check.
    new-rdkit-env3) [osmart@ebi-cli-003 ccd_utils]$ nosetests -v tests/test_write_ccd_cif.py
    tests.test_write_ccd_cif.test_load_eoh_from_cif_write_it_out(True, 'have written cif file /nfs/msd/work2/osmart/ccd_utils/tests/out/EOH_test_write.cif') ... ok
    tests.test_write_ccd_cif.test_load_eoh_from_cif_write_it_out('EOH', 'EOH', 'readback chem_comp_id, with cif_parser=PDBeCIF') ... ok
    tests.test_write_ccd_cif.test_load_eoh_from_cif_write_it_out('LFQSCWFLJHTTHZ-UHFFFAOYSA-N', 'LFQSCWFLJHTTHZ-UHFFFAOYSA-N', 'readback inchikey') ... ok
    tests.test_write_ccd_cif.test_load_eoh_from_cif_write_it_out(<pdb_chemical_components.PdbChemicalComponents object at 0x7f205b6e56a0>, <pdb_chemical_components.PdbChemicalComponents object at 0x7f205919b4e0>, 'check equality of orig_pdbccd and read_back_pdb_ccd') ... FAIL

    ======================================================================
    FAIL: tests.test_write_ccd_cif.test_load_eoh_from_cif_write_it_out(<pdb_chemical_components.PdbChemicalComponents object at 0x7f205b6e56a0>, <pdb_chemical_components.PdbChemicalComponents object at 0x7f205919b4e0>, 'check equality of orig_pdbccd and read_back_pdb_ccd')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
    AssertionError: <pdb_chemical_components.PdbChemicalComponents object at 0x7f205b6e56a0> != <pdb_chemical_components.PdbChemicalComponents object at 0x7f205919b4e0> : check equality of orig_pdbccd and read_back_pdb_ccd

    ----------------------------------------------------------------------
    Ran 4 tests in 0.032s

    FAILED (failures=1)

For issue #9 Split wwPDB chemical component dictionary file into separate cif file for each component