Add more tests on eoh bonds.
Currently get failures:

nosetests test_pdb_chemical_components.py
                ................................FE
                ======================================================================
                ERROR: Failure: IndexError (list index out of range)
                ----------------------------------------------------------------------
                Traceback (most recent call last):
                  File "/ebi/msd/work2/msdsd/onedep/da_top/tools-redhat-7/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
                    for test in g():
                  File "/nfs/msd/work2/osmart/ccd_utils/test_pdb_chemical_components.py", line 69, in test_load_eoh_from_cif
                    third_bond = eoh.bonds[2]
                IndexError: list index out of range

                ======================================================================
                FAIL: test_pdb_chemical_components.test_load_eoh_from_cif(8, 0, 'number_bonds, with cif_parser=CifFile')
                ----------------------------------------------------------------------
                Traceback (most recent call last):
                  File "/ebi/msd/work2/msdsd/onedep/da_top/tools-redhat-7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
                    self.test(*self.arg)
                AssertionError: number_bonds, with cif_parser=CifFile

                ----------------------------------------------------------------------
                Ran 34 tests in 0.081s

                FAILED (errors=1, failures=1)

  Need to code bond parsing for cif_parser=CifFile