refactor process_components_cif_cli.py split off writing coordinate files to separate method _write_coordinate_files_for_ccd(....) before dealing with image files.
for issue #13 "Script to read wwPDB chemical component dictionary and split it to produce PDBeChem outputs"

Unit test still fails because no xml images yet:

        (new-rdkit-env) [osmart@ebi-cli-003 ccd_utils]$ nosetests tests/test_process_components_cif_cli.py
        usage: nosetests [-h] [--debug] COMPONENTS_CIF OUTPUT_DIR
        nosetests: error: too few arguments
        ....................................................................FFFFFFFFFFFFFFFFFFF
        ======================================================================
        FAIL: tests.test_process_components_cif_cli.test_with_components_cif_first_file_comps(False, 'images sub-directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/images must be created')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
            self.test(*self.arg)
        AssertionError: images sub-directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/images must be created

        Ran 87 tests in 0.260s

        FAILED (failures=19)