cml file writing Sort "TypeError: write() argument must be str, not bytes" bug in python Solution from: https://stackoverflow.com/questions/5512811/builtins-typeerror-must-be-str-not-bytes for issue #10 (writing cml)
 Switch to python caused issue with cml test:
                 (new-rdkit-env3) [osmart@ebi-cli-003 ccd_utils]$ nosetests -v tests/test_write_cml.py
                tests.test_write_cml.test_load_eoh_from_cif('ETHANOL', 'ETHANOL', 'cml_file_or_string must provide correct systematic name') ... ok
                tests.test_write_cml.test_load_eoh_from_cif('0', '0', 'cml_file_or_string must provide correct formal charge') ... ok
                Failure: TypeError (write() argument must be str, not bytes) ... ERROR
                tests.test_write_cml.test_load_atp_from_cif('Nc1ncnc2n(cnc12)[C@@H]3O[C@H](CO[P@](O)(=O)O[P@@](O)(=O)O[P](O)(O)=O)[C@@H](O)[C@H]3O', 'Nc1ncnc2n(cnc12)[C@@H]3O[C@H](CO[P@](O)(=O)O[P@@](O)(=O)O[P](O)(O)=O)[C@@H](O)[C@H]3O', 'cml_file_or_string must provide correct stereo smiles') ... ok
                tests.test_write_cml.test_load_atp_from_cif('O=P(O)(O)OP(=O)(O)OP(=O)(O)OCC3OC(n2cnc1c(ncnc12)N)C(O)C3O', 'O=P(O)(O)OP(=O)(O)OP(=O)(O)OCC3OC(n2cnc1c(ncnc12)N)C(O)C3O', 'cml_file_or_string must provide correct nonstereo smiles') ... ok

                ======================================================================
                ERROR: Failure: TypeError (write() argument must be str, not bytes)
                ----------------------------------------------------------------------
                Traceback (most recent call last):
                  File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
                    raise self.exc_val.with_traceback(self.tb)
                  File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
                    for test in g():
                  File "/nfs/msd/work2/osmart/ccd_utils/tests/test_write_cml.py", line 40, in test_load_eoh_from_cif
                    eoh.cml_file_or_string(file_name=cml)
                  File "/nfs/msd/work2/osmart/ccd_utils/pdb_chemical_components_rdkit.py", line 286, in cml_file_or_string
                    cml_file.write(cml_string)
                TypeError: write() argument must be str, not bytes

After fix:__________________________________________________________________________________
                (new-rdkit-env3) [osmart@ebi-cli-003 ccd_utils]$ nosetests -v tests/test_write_cml.py
                tests.test_write_cml.test_load_eoh_from_cif('ETHANOL', 'ETHANOL', 'cml_file_or_string must provide correct systematic name') ... ok
                tests.test_write_cml.test_load_eoh_from_cif('0', '0', 'cml_file_or_string must provide correct formal charge') ... ok
                tests.test_write_cml.test_load_eoh_from_cif(True, 'EOH call to eoh.cml_file_or_string(file="/nfs/msd/work2/osmart/ccd_utils/tests/out/EOH.cml") must create a non-empty file.') ... ok
                tests.test_write_cml.test_load_atp_from_cif('Nc1ncnc2n(cnc12)[C@@H]3O[C@H](CO[P@](O)(=O)O[P@@](O)(=O)O[P](O)(O)=O)[C@@H](O)[C@H]3O', 'Nc1ncnc2n(cnc12)[C@@H]3O[C@H](CO[P@](O)(=O)O[P@@](O)(=O)O[P](O)(O)=O)[C@@H](O)[C@H]3O', 'cml_file_or_string must provide correct stereo smiles') ... ok
                tests.test_write_cml.test_load_atp_from_cif('O=P(O)(O)OP(=O)(O)OP(=O)(O)OCC3OC(n2cnc1c(ncnc12)N)C(O)C3O', 'O=P(O)(O)OP(=O)(O)OP(=O)(O)OCC3OC(n2cnc1c(ncnc12)N)C(O)C3O', 'cml_file_or_string must provide correct nonstereo smiles') ... ok

                ----------------------------------------------------------------------
                Ran 5 tests in 0.057s

                OK