Test specifying an input file that does not exist raises an IOError in SplitComponentsCif
for issue #17 process_components_cif script to read complete components.cif and produce PDBeChem ftp area

Initially fails:

    (new-rdkit-env3) [osmart@swannandrh6d pdbeccdutils]$ nosetests /ebi/msd/work2/osmart/ccd_utils/pdbeccdutils/tests/test_split_components_cif.py
    ..F......
    ======================================================================
    FAIL: test_loading_file_that_does_not_exist_raises_ioerror (tests.test_split_components_cif.TestSplitComponentsCif)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/ebi/msd/work2/osmart/ccd_utils/pdbeccdutils/tests/test_split_components_cif.py", line 40, in test_loading_file_that_does_not_exist_raises_ioerror
        SplitComponentsCif('/////impossible')
    AssertionError: OSError not raised
    -------------------- >> begin captured stdout << ---------------------
    The file provided does not exist or is not a file.

    --------------------- >> end captured stdout << ----------------------

    ----------------------------------------------------------------------
    Ran 9 tests in 0.088s

    FAILED (failures=1)