Add test for the 00O label OXT as H37 bug.
For issue #20

This currently fails as it should:
    (new-rdkit-env) osmart@fuji01vm:~/ccd_utils$ nosetests pdbeccdutils/tests/test_write_img.py
    ...........[16:30:47] Explicit valence for atom # 2 Be, 4, is greater than permitted
    ....[16:30:47] Explicit valence for atom # 20 C, 5, is greater than permitted
    ..[16:30:47] Explicit valence for atom # 0 B, 6, is greater than permitted
    ........................................................[16:30:48] Explicit valence for atom # 0 B, 6, is greater than permitted
    .FF
    ======================================================================
    FAIL: pdbeccdutils.tests.test_write_img.test_00O_labels_have_OXT_not_H37(False, '00O: The svg file must contain the atom name OXT')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/osmart/anaconda/envs/new-rdkit-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    AssertionError: 00O: The svg file must contain the atom name OXT
    -------------------- >> begin captured logging << --------------------
    root: DEBUG: RDKit setup for PDB CCD chem_comp_id 00O
    root: DEBUG: _setup_atoms:
    root: DEBUG: _setup_bonds:
    root: DEBUG: _setup_conformers:
    root: DEBUG: removeH from original:
    root: DEBUG: SanitizeMol rdkit_mol_cleaned
    root: DEBUG: Kekulize rdkit_mol_cleaned
    root: DEBUG: call to __create_xyz_2d with hydrogen=False
    --------------------- >> end captured logging << ---------------------

    ======================================================================
    FAIL: pdbeccdutils.tests.test_write_img.test_00O_labels_have_OXT_not_H37(True, '00O: The svg file must  not contain the atom name H37')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/osmart/anaconda/envs/new-rdkit-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    AssertionError: 00O: The svg file must  not contain the atom name H37

    ----------------------------------------------------------------------
    Ran 76 tests in 0.784s