unit test for chem.xml creation and contents by process_components_cif_cli
For issue #10 "Create chem.xml for all components"

Initially test fails because of lack of implementation:
    (new-rdkit-env3) [osmart@ebi-cli-003 ccd_utils]$ nosetests  tests/test_process_components_cif_cli.py
    usage: nosetests [-h] [--debug] COMPONENTS_CIF OUTPUT_DIR
    nosetests: error: the following arguments are required: COMPONENTS_CIF, OUTPUT_DIR
    ................................................................F
    ======================================================================
    FAIL: tests.test_process_components_cif_cli.test_with_components_cif_first_file_comps(False, 'problem opening chem.xml "[Errno 2] No such file or directory: \'/nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/chem.xml\'"')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
    AssertionError: False is not true : problem opening chem.xml "[Errno 2] No such file or directory: '/nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/chem.xml'"

    ----------------------------------------------------------------------
    Ran 65 tests in 0.214s

    FAILED (failures=1)