For #3 Created test that calls sdf_file_or_string with ideal=False to process sdf with model coordinates. Test fails as expected because the method for model coordinates has not been coded
ERROR: Failure: NotImplementedError (sdf_file_or_string ideal=False to be coded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qyuan/anaconda2/envs/my-rdkit-env/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/qyuan/pdbe/ccd_utils/test_pdb_chemical_components_rdkit.py", line 43, in test_hard_code_cmo
    sdf_string_model = cmo.sdf_file_or_string(ideal=False)
  File "/home/qyuan/pdbe/ccd_utils/pdb_chemical_components_rdkit.py", line 87, in sdf_file_or_string
    raise NotImplementedError('sdf_file_or_string ideal=False to be coded')  # TODO implement ideal
NotImplementedError: sdf_file_or_string ideal=False to be coded