unit test for xyz format. For issue #21 "write xyz format file for PDB-CCD"
stub version of xyz_file_or_string method causes tests to fail as they should:

         (new-rdkit-env3) [osmart@ebi-cli-003 ccd_utils]$ nosetests -v tests/test_write_xyz.py
        tests.test_write_xyz.test_xyz_for_eoh_ideal(1, 11, 'EOH xyz format should have 11 lines') ... FAIL
        tests.test_write_xyz.test_xyz_for_eoh_ideal('xyz_file_or_string not yet implemented', 9, 'EOH xyz should start with 9 the number of atoms') ... FAIL
        Failure: IndexError (list index out of range) ... ERROR
        Failure: IndexError (list index out of range) ... ERROR

        ======================================================================
        ERROR: Failure: IndexError (list index out of range)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
            raise self.exc_val.with_traceback(self.tb)
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
            for test in g():
          File "/nfs/msd/work2/osmart/ccd_utils/tests/test_write_xyz.py", line 31, in test_xyz_for_eoh_ideal
            yield assert_equals, lines[1], 'EOH', 'EOH xyz 2nd line should be "EOH"'
        IndexError: list index out of range

        ======================================================================
        ERROR: Failure: IndexError (list index out of range)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
            raise self.exc_val.with_traceback(self.tb)
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
            for test in g():
          File "/nfs/msd/work2/osmart/ccd_utils/tests/test_write_xyz.py", line 39, in test_xyz_for_eoh_model
            yield assert_in, '7.491', lines[2], 'EOH xyz first atom record z coordinate'
        IndexError: list index out of range

        ======================================================================
        FAIL: tests.test_write_xyz.test_xyz_for_eoh_ideal(1, 11, 'EOH xyz format should have 11 lines')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
            self.test(*self.arg)
        AssertionError: 1 != 11 : EOH xyz format should have 11 lines

        ======================================================================
        FAIL: tests.test_write_xyz.test_xyz_for_eoh_ideal('xyz_file_or_string not yet implemented', 9, 'EOH xyz should start with 9 the number of atoms')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
            self.test(*self.arg)
        AssertionError: 'xyz_file_or_string not yet implemented' != 9 : EOH xyz should start with 9 the number of atoms

        ----------------------------------------------------------------------
        Ran 4 tests in 0.031s