Tidy up: alter test_pdb_chemical_components.py so that by default it uses cif_parser='auto' rather than trying both.
environment variable TEST_CIF_PARSER_ALL can be set to try both. Example run:

        (new-rdkit-env) osmart@fuji01vm:~/ccd_utils$ env | grep TEST_CIF_PARSER_ALL
        (new-rdkit-env) osmart@fuji01vm:~/ccd_utils$ nosetests -s test_pdb_chemical_components.py 2>&1
        ....................................
        ----------------------------------------------------------------------
        Ran 36 tests in 0.034s

        OK
        (new-rdkit-env) osmart@fuji01vm:~/ccd_utils$ export TEST_CIF_PARSER_ALL='yes'
        (new-rdkit-env) osmart@fuji01vm:~/ccd_utils$ nosetests -s test_pdb_chemical_components.py 2>&1
        .................F...................
        ======================================================================
        FAIL: test_pdb_chemical_components.test_eoh_loads_with_parser(0, 1, "Import problem using cif_parser='CifFile' message='No module named pdbx_v2.core.CifFile'. Other tests will skip using testing this parser.")
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/home/osmart/anaconda/envs/new-rdkit-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
            self.test(*self.arg)
        AssertionError: Import problem using cif_parser='CifFile' message='No module named pdbx_v2.core.CifFile'. Other tests will skip using testing this parser.

        ----------------------------------------------------------------------
        Ran 37 tests in 0.038s

        FAILED (failures=1)