alter unittest for the process_components_cif_cli.py command line script based to use nose yield subtests.
how to use nose test generators in class: https://stackoverflow.com/questions/6689537/nose-test-generators-inside-class
how to use nose assert_raises: https://stackoverflow.com/questions/11767938/how-to-use-noses-assert-raises

For issue #13 "Script to read wwPDB chemical component dictionary and split it to produce PDBeChem outputs"

currently (sub)tests fail because of lack of implementation:

(new-rdkit-env3) [osmart@ebi-cli-003 ccd_utils]$ nosetests -v tests/test_process_components_cif_cli.py
nose.tools.trivial.Dummy.test_with_components_cif_first_file_comps(False, 'output directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli must be created') ... FAIL
nose.tools.trivial.Dummy.test_with_components_cif_first_file_comps(False, 'files sub-directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/files must be created') ... FAIL
nose.tools.trivial.Dummy.test_with_components_cif_first_file_comps(False, 'mmcif sub-directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/files/mmcif must be created') ... FAIL
User passes no args, should produce a usage statement and then raise SystemExit. Usage statement will start ... usage: nosetests [-h] [--debug] COMPONENTS_CIF OUTPUT_DIR
nosetests: error: the following arguments are required: COMPONENTS_CIF, OUTPUT_DIR
ok

======================================================================
FAIL: nose.tools.trivial.Dummy.test_with_components_cif_first_file_comps(False, 'output directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli must be created')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: False is not true : output directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli must be created
-------------------- >> begin captured logging << --------------------
 : DEBUG: components_cif=/nfs/msd/work2/osmart/ccd_utils/tests/components_cif/components.cif.first_five_comps output_dir=/nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: nose.tools.trivial.Dummy.test_with_components_cif_first_file_comps(False, 'files sub-directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/files must be created')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: False is not true : files sub-directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/files must be created

======================================================================
FAIL: nose.tools.trivial.Dummy.test_with_components_cif_first_file_comps(False, 'mmcif sub-directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/files/mmcif must be created')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ebi/msd/work2/osmart/conda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
AssertionError: False is not true : mmcif sub-directory /nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli/files/mmcif must be created

----------------------------------------------------------------------
Ran 4 tests in 0.005s

FAILED (failures=3)