Add unittest for the process_components_cif_cli.py command line script based on http://dustinrcollins.com/testing-python-command-line-apps approach.
For issue #13 "Script to read wwPDB chemical component dictionary and split it to produce PDBeChem outputs"

Initially fails because have not yet implemented:

        (new-rdkit-env3) [osmart@ebi-cli-003 ccd_utils]$ nosetests -v tests/test_process_components_cif_cli.py
        test_with_components_cif_first_file_comps (tests.test_process_components_cif_cli.ProcessComponentsCIFTestCase) ... ERROR
        User passes no args, should fail with SystemExit ... usage: nosetests [-h] [--debug] COMPONENTS_CIF OUTPUT_DIR
        nosetests: error: the following arguments are required: COMPONENTS_CIF, OUTPUT_DIR
        ok

        ======================================================================
        ERROR: test_with_components_cif_first_file_comps (tests.test_process_components_cif_cli.ProcessComponentsCIFTestCase)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/nfs/msd/work2/osmart/ccd_utils/tests/test_process_components_cif_cli.py", line 35, in test_with_components_cif_first_file_comps
            process_components_cif(args.COMPONENTS_CIF, args.OUTPUT_DIR,  args.debug)
          File "/nfs/msd/work2/osmart/ccd_utils/process_components_cif_cli.py", line 64, in process_components_cif
            raise NotImplementedError('process_components_cif not yet implemented')
        NotImplementedError: process_components_cif not yet implemented
        -------------------- >> begin captured logging << --------------------
         : DEBUG: components_cif=/nfs/msd/work2/osmart/ccd_utils/tests/components_cif/components.cif.first_five_comps output_dir=/nfs/msd/work2/osmart/ccd_utils/tests/out/test_process_components_cif_cli
        --------------------- >> end captured logging << ---------------------

        ----------------------------------------------------------------------
        Ran 2 tests in 0.005s

        FAILED (errors=1)