Unittest bug 7OM causes process_component_cif_cli to fall over because it lacks an inchikey.
Test test_with_problematic_cif_7om fails with the same error:

ERROR: Failure: TypeError ('NoneType' object is not subscriptable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osmart/anaconda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/osmart/anaconda/envs/new-rdkit-env3/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
    for test in g():
  File "/home/osmart/ccd_utils/pdbeccdutils/tests/test_process_components_cif_cli.py", line 34, in test_with_problematic_cif_7om
    process_components_cif(args.COMPONENTS_CIF, args.OUTPUT_DIR, args.debug)
  File "/home/osmart/ccd_utils/pdbeccdutils/process_components_cif_cli.py", line 106, in process_components_cif
    if pdb_cc_rdkit.inchikey[:14] != pdb_cc_rdkit.inchikey_from_rdkit[:14]:
TypeError: 'NoneType' object is not subscriptable